version: '3'

services:
    localstack:
        image: localstack/localstack
        container_name: aws-localstack-fn-go-hello
        ports:
          - "4567-4584:4567-4584"
          - "${PORT_WEB_UI-8888}:${PORT_WEB_UI-8888}"
        environment:
          - USE_SSL=true
          - SERVICES=${SERVICES-lambda }
          - DEBUG=${DEBUG- }
          - DATA_DIR=${DATA_DIR- }
          - PORT_WEB_UI=${PORT_WEB_UI- }
          - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
          - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
          - DOCKER_HOST=unix:///var/run/docker.sock
        volumes:
          - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
