version: '3'

services:
  localstack:
    image: localstack/localstack
    container_name: aws-localstack-fn-go-hello
    ports:
      - "4566:4566"
    environment:
      SERVICES: "lambda,s3"
      DATA_DIR: "/tmp/localstack/data"
      LAMDA_EXECUTER: "docker"
      LAMBDA_REMOTE_DOCKER: "false"
      LOCALSTACK_HOSTNAME: "localhost"
      DEBUG: "true"
    volumes:
      - ./.localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
