version: '3'

services:
  localstack:
    image: localstack/localstack
    container_name: awslocalstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=${SERVICES-lambda, s3 }
      - DATA_DIR= "/tmp/localstack/data"
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- docker-reuse}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
      - DEBUG=${DEBUG- }
    volumes:
      - ./.localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
